services:
  server:
    build: 
      context: ./server
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - app_network
    volumes:
      - ./server:/app
      - static_data:/app/staticfiles
    env_file:
      - ./server/.env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=data
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - REDIS_URL=redis://redis:6379/0

  celery_worker:
    build: 
      context: ./server
      dockerfile: dockerfile
    command: celery -A server worker -l info
    depends_on:
      - db
      - redis
      - server
    networks:
      - app_network
    volumes:
      - ./server:/app
    env_file:
      - ./server/.env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=data
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - REDIS_URL=redis://redis:6379/0

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=data
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - app_network

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - app_network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api/v1
    networks:
      - app_network
    depends_on:
      - server

volumes:
  postgres_data:
  static_data:

networks:
  app_network:
    driver: bridge
