# Generated by Django 4.2.17 on 2026-06-01 10:16

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('role', models.CharField(blank=True, choices=[('SCHOOL_ADMIN', 'SCHOOL_ADMIN'), ('SCHOOL_TEACHER', 'SCHOOL_TEACHER'), ('SCHOOL_STUDENT', 'SCHOOL_STUDENT'), ('SCHOOL_PARENT', 'SCHOOL_PARENT'), ('SCHOOL_STAFF', 'SCHOOL_STAFF')], max_length=32, null=True)),
                ('status', models.BooleanField(default=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=64, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_no', models.CharField(max_length=20, unique=True)),
                ('established_year', models.PositiveIntegerField()),
                ('campus_type', models.CharField(choices=[('CLASS', 'CLASS'), ('VERTICAL_CAMPUS', 'VERTICAL_CAMPUS'), ('OTHER', 'OTHER')], max_length=32)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='schools/logos/')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('PENDING', 'PENDING'), ('BLOCKED', 'BLOCKED')], default='PENDING', max_length=16)),
                ('created_by', models.UUIDField()),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolAdmin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='admin_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('admin_code', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolPrincipal',
            fields=[
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='principal', serialize=False, to='api.school')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='schools/principals/photos/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='schools/principals/signatures/')),
                ('identity_proof_doc', models.ImageField(blank=True, null=True, upload_to='schools/principals/identity/')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='staff_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('employee_id', models.CharField(max_length=64, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('admission_no', models.CharField(max_length=64, unique=True)),
                ('roll_no', models.CharField(max_length=64, unique=True)),
                ('class_id', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='teacher_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('employee_id', models.CharField(max_length=64, unique=True)),
                ('qualification', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolDomain',
            fields=[
                ('domain_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subdomain', models.CharField(max_length=120, unique=True)),
                ('full_domain', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('PENDING', 'PENDING'), ('BLOCKED', 'BLOCKED')], default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='domain', to='api.school')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolAddress',
            fields=[
                ('address_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=20)),
                ('full_address', models.TextField()),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='api.school')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.school'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='parent_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('relation', models.CharField(max_length=64)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='api.student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('school', 'email'), name='uniq_user_email_per_school'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('school', 'phone_no'), name='uniq_user_phone_per_school'),
        ),
    ]
