# Generated by Django 4.2.17 on 2026-06-02 08:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeAccount',
            fields=[
                ('fee_account_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_year', models.CharField(max_length=32)),
                ('total_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(blank=True, default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('inquiry_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=255)),
                ('parent_name', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('grade_interested', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('INQUIRY', 'INQUIRY'), ('INQUIRY_CONVERTED', 'INQUIRY_CONVERTED'), ('REGISTERED', 'REGISTERED'), ('ADMISSION_REJECTED', 'ADMISSION_REJECTED'), ('CANCELLED', 'CANCELLED')], default='INQUIRY', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='api.school')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='blood_group',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='student',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_no',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/photos/'),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='api.school'),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='StudentFeePayment',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_mode', models.CharField(max_length=50)),
                ('transaction_ref', models.CharField(blank=True, default='', max_length=100)),
                ('fee_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.feeaccount')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAddress',
            fields=[
                ('address_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=20)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('registration_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('INQUIRY', 'INQUIRY'), ('INQUIRY_CONVERTED', 'INQUIRY_CONVERTED'), ('REGISTERED', 'REGISTERED'), ('ADMISSION_REJECTED', 'ADMISSION_REJECTED'), ('CANCELLED', 'CANCELLED')], default='REGISTERED', max_length=32)),
                ('registration_date', models.DateField(default=django.utils.timezone.now)),
                ('applied_for_class', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('inquiry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration', to='api.inquiry')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='api.school')),
            ],
        ),
        migrations.CreateModel(
            name='GuardianInfo',
            fields=[
                ('guardian_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('relation', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('occupation', models.CharField(blank=True, default='', max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='api.student')),
            ],
        ),
        migrations.AddField(
            model_name='feeaccount',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_account', to='api.student'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=100)),
                ('file_url', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='ClassEnrollment',
            fields=[
                ('enrollment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('class_id', models.CharField(max_length=64)),
                ('section_id', models.CharField(max_length=64)),
                ('academic_year', models.CharField(max_length=32)),
                ('roll_no', models.CharField(max_length=64)),
                ('admission_no', models.CharField(max_length=64)),
                ('status', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('admission_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admission_no', models.CharField(max_length=64, unique=True)),
                ('admission_date', models.DateField(default=django.utils.timezone.now)),
                ('academic_year', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('INQUIRY', 'INQUIRY'), ('INQUIRY_CONVERTED', 'INQUIRY_CONVERTED'), ('REGISTERED', 'REGISTERED'), ('ADMISSION_REJECTED', 'ADMISSION_REJECTED'), ('CANCELLED', 'CANCELLED')], default='REGISTERED', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='api.registration')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='api.school')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='admission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to='api.admission'),
        ),
    ]
