# Generated by Django 4.2.17 on 2026-06-02 11:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


def merge_registration_and_admission(apps, schema_editor):
    Student = apps.get_model("api", "Student")
    Registration = apps.get_model("api", "Registration")
    Admission = apps.get_model("api", "Admission")
    StudentAdmission = apps.get_model("api", "StudentAdmission")

    used_registration_ids = set()

    for student in Student.objects.all():
        registration = Registration.objects.filter(pk=getattr(student, "registration_id", None)).first()
        admission = Admission.objects.filter(pk=getattr(student, "admission_id", None)).first()
        school = student.school or getattr(admission, "school", None) or getattr(registration, "school", None)

        StudentAdmission.objects.create(
            school=school,
            student=student,
            inquiry=getattr(registration, "inquiry", None),
            admission_type=getattr(registration, "admission_type", "DIRECT_REGISTRATION"),
            admission_no=getattr(admission, "admission_no", student.admission_no),
            status=getattr(admission, "status", getattr(registration, "status", "REGISTERED")),
            admission_date=getattr(admission, "admission_date", getattr(registration, "registration_date", django.utils.timezone.now().date())),
            applied_for_class=getattr(registration, "applied_for_class", student.class_id),
            academic_year=getattr(admission, "academic_year", ""),
            remarks=getattr(admission, "notes", getattr(registration, "remarks", "")),
            created_at=getattr(registration, "created_at", django.utils.timezone.now()),
        )

        if registration:
            used_registration_ids.add(registration.pk)

    for registration in Registration.objects.exclude(pk__in=used_registration_ids):
        linked_admission = Admission.objects.filter(registration=registration).first()
        StudentAdmission.objects.create(
            school=registration.school,
            inquiry=registration.inquiry,
            admission_type=registration.admission_type,
            admission_no=getattr(linked_admission, "admission_no", f"REG-{registration.pk}"),
            status=getattr(linked_admission, "status", registration.status),
            admission_date=getattr(linked_admission, "admission_date", registration.registration_date),
            applied_for_class=registration.applied_for_class,
            academic_year=getattr(linked_admission, "academic_year", ""),
            remarks=getattr(linked_admission, "notes", registration.remarks),
            created_at=registration.created_at,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_student_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAdmission',
            fields=[
                ('admission_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admission_type', models.CharField(choices=[('DIRECT_REGISTRATION', 'DIRECT_REGISTRATION'), ('INQUIRY_THEN_REGISTRATION', 'INQUIRY_THEN_REGISTRATION')], max_length=32)),
                ('admission_no', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('INQUIRY', 'INQUIRY'), ('INQUIRY_CONVERTED', 'INQUIRY_CONVERTED'), ('REGISTERED', 'REGISTERED'), ('ADMISSION_REJECTED', 'ADMISSION_REJECTED'), ('CANCELLED', 'CANCELLED')], default='REGISTERED', max_length=32)),
                ('admission_date', models.DateField(default=django.utils.timezone.now)),
                ('applied_for_class', models.CharField(max_length=100)),
                ('academic_year', models.CharField(max_length=32)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('inquiry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_admission', to='api.inquiry')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_admissions', to='api.school')),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='api.student')),
            ],
        ),
        migrations.RunPython(merge_registration_and_admission, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='registration',
            name='inquiry',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='school',
        ),
        migrations.RemoveField(
            model_name='student',
            name='admission',
        ),
        migrations.RemoveField(
            model_name='student',
            name='registration',
        ),
        migrations.DeleteModel(
            name='Admission',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
