# Generated by Django 4.2.17 on 2026-06-03 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_studentadmission_remove_registration_inquiry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schooladmin',
            name='user',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.DeleteModel(
            name='SchoolAdmin',
        ),
    ]
