# Generated by Django 6.0 on 2025-12-22 10:33

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.BigIntegerField(default=api.models.generate_account_number, editable=False, unique=True),
        ),
    ]
