# Generated by Django 4.2.17 on 2026-06-03 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_staff_created_at_staff_join_date_staff_profile_image_and_more'),
    ]

    operations = []
