# Generated by Django 4.2.17 on 2026-06-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_staff_created_at_staff_join_date_staff_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
