# Generated by Django 4.2.17 on 2026-06-04 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_salarypayment_payment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam_name', models.CharField(max_length=255)),
                ('academic_year', models.CharField(max_length=32)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='SCHEDULED', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='api.school')),
            ],
            options={
                'unique_together': {('school', 'exam_name', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='ExamTimetable',
            fields=[
                ('timetable_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_marks', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('passing_marks', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('room_no', models.CharField(blank=True, default='', max_length=64)),
                ('instructions', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='api.exam')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_timetables', to='api.school')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_timetables', to='api.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_timetables', to='api.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_timetables', to='api.teacher')),
            ],
            options={
                'ordering': ('exam_date', 'start_time'),
                'unique_together': {('exam', 'school_class', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('mark_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=6)),
                ('grade', models.CharField(blank=True, default='', max_length=16)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='api.examtimetable')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marks_entered', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='api.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_marks', to='api.student')),
            ],
            options={
                'ordering': ('student__roll_no', 'student__admission_no'),
                'unique_together': {('exam_timetable', 'student')},
            },
        ),
    ]
