# Generated by Django 4.2.17 on 2026-06-11 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_teacher_assigned_classes_and_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentattendance',
            name='school_class',
        ),
    ]
