# Generated by Django 4.2.17 on 2026-06-11 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_studentattendance_school_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='campus_type',
        ),
    ]
