# Generated by Django 4.2.17 on 2026-06-15 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_collune_schema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
