# Generated by Django 4.2.17 on 2026-06-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_creator_preferences_and_social_platforms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatorsocialaccount',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='creatorsocialaccount',
            name='url',
        ),
        migrations.AlterField(
            model_name='creatorsocialaccount',
            name='platform',
            field=models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('YOUTUBE', 'YouTube'), ('LINKEDIN', 'LinkedIn'), ('X', 'X'), ('FACEBOOK', 'Facebook'), ('TIKTOK', 'TikTok'), ('SNAPCHAT', 'Snapchat')], max_length=24),
        ),
    ]
