# Generated by Django 4.2.17 on 2026-06-17 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_campaign_builder_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='budget_max',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='budget_min',
        ),
    ]
