# Generated by Django 4.2.17 on 2026-06-18 19:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_campaign_budget_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignStatusSummary',
            fields=[
                ('summary_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('applications_received', models.PositiveIntegerField(default=0)),
                ('recommended_creators', models.PositiveIntegerField(default=0)),
                ('collaborations_started', models.PositiveIntegerField(default=0)),
                ('applications_close_in_days', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status_summary', to='api.campaign')),
            ],
            options={
                'verbose_name_plural': 'campaign status summaries',
            },
        ),
        migrations.CreateModel(
            name='CampaignProgress',
            fields=[
                ('progress_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('IN_PROGRESS', 'In progress'), ('UPCOMING', 'Upcoming')], default='UPCOMING', max_length=24)),
                ('display_date', models.CharField(blank=True, default='', max_length=80)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_steps', to='api.campaign')),
            ],
            options={
                'verbose_name_plural': 'campaign progress',
                'ordering': ('sort_order', 'created_at'),
                'unique_together': {('campaign', 'title')},
            },
        ),
    ]
