# Generated by Django 4.2.17 on 2026-06-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_campaignstatussummary_campaignprogress'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='creatorsocialaccount',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='creatorsocialaccount',
            name='access_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='creatorsocialaccount',
            name='audience_country',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='creatorsocialaccount',
            name='engagement_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='creatorsocialaccount',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creatorsocialaccount',
            name='followers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creatorsocialaccount',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creatorsocialaccount',
            name='media_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creatorsocialaccount',
            name='refresh_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='creatorsocialaccount',
            name='social_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='creatorsocialaccount',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='creatorsocialaccount',
            name='username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
