# Generated by Django 4.2.17 on 2026-06-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_creatorsocialaccount_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorsocialaccount',
            name='provider_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='creatorsocialaccount',
            name='view_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
