# Generated by Django 4.2.17 on 2026-07-10 06:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_creatorsocialaccount_youtube_analytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorSavedCampaign',
            fields=[
                ('saved_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.RemoveField(
            model_name='campaignstatussummary',
            name='campaign',
        ),
        migrations.RenameField(
            model_name='creatorsocialaccount',
            old_name='audience_country',
            new_name='analytics',
        ),
        migrations.RenameField(
            model_name='creatorsocialaccount',
            old_name='youtube_long_video_count',
            new_name='video_count',
        ),
        migrations.RenameField(
            model_name='creatorsocialaccount',
            old_name='youtube_videos',
            new_name='videos',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='status',
            new_name='is_profile_visible',
        ),
        migrations.RemoveField(
            model_name='brandprofile',
            name='profile_completion',
        ),
        migrations.RemoveField(
            model_name='brandprofile',
            name='verification_status',
        ),
        migrations.RemoveField(
            model_name='brandshortlist',
            name='timeline',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='status',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='audience_size',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='open_to_travel',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='portfolio_url',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='preferred_response_time',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='rate_max',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='rate_min',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='verification_status',
        ),
        migrations.RemoveField(
            model_name='creatorsocialaccount',
            name='youtube_analytics',
        ),
        migrations.RemoveField(
            model_name='creatorsocialaccount',
            name='youtube_short_video_count',
        ),
        migrations.AddField(
            model_name='brandshortlist',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandshortlist',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='work_with',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending review'), ('VERIFIED', 'Verified')], default='PENDING', max_length=24),
        ),
        migrations.AlterField(
            model_name='brandshortlist',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted')], default='DRAFT', max_length=32),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='campaigns/covers/'),
        ),
        migrations.AlterField(
            model_name='campaignapplication',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=24),
        ),
        migrations.AlterField(
            model_name='creatorsocialaccount',
            name='platform',
            field=models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('YOUTUBE', 'YouTube'), ('X', 'X'), ('FACEBOOK', 'Facebook')], max_length=24),
        ),
        migrations.DeleteModel(
            name='CampaignProgress',
        ),
        migrations.DeleteModel(
            name='CampaignStatusSummary',
        ),
        migrations.AddField(
            model_name='creatorsavedcampaign',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='api.campaign'),
        ),
        migrations.AddField(
            model_name='creatorsavedcampaign',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_campaigns', to='api.creatorprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='creatorsavedcampaign',
            unique_together={('campaign', 'creator')},
        ),
    ]
