# Generated by Django 4.2.17 on 2026-07-25 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_creatorsavedcampaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='ip_restriction',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='is_two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='location_branch',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='user',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='team_assignment',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('OPERATIONS_MANAGER', 'Operations Manager'), ('SALES_MARKETING_MANAGER', 'Sales & Marketing Manager'), ('PROJECT_MANAGER', 'Project Manager'), ('ANALYTICS_MANAGER', 'Analytics Manager'), ('TEAM_MEMBER', 'Team Member / Executive'), ('BRAND', 'Brand'), ('CREATOR', 'Creator')], default='CREATOR', max_length=32),
        ),
    ]
