# Generated by Django 4.2.17 on 2026-07-30 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_remove_user_internal_metadata_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('BRAND', 'Brand'), ('CREATOR', 'Creator')], default='CREATOR', max_length=32),
        ),
        migrations.CreateModel(
            name='UserAdminRole',
            fields=[
                ('role_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_name', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('OPERATIONS_MANAGER', 'Operations Manager'), ('SALES_MARKETING_MANAGER', 'Sales & Marketing Manager'), ('PROJECT_MANAGER', 'Project Manager'), ('ANALYTICS_MANAGER', 'Analytics Manager'), ('TEAM_MEMBER', 'Team Member / Executive')], default='TEAM_MEMBER', max_length=32)),
                ('permissions', models.TextField()),
                ('Purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
