# Generated by Django 4.2.17 on 2026-08-13 17:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_creatorprofile_structured_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandSavedCreator',
            fields=[
                ('saved_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_creators', to='api.brandprofile')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_brands', to='api.creatorprofile')),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('brand', 'creator')},
            },
        ),
    ]
