# Generated by Django 4.2.17 on 2026-08-15 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_brandprofile_expanded_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandprofile',
            name='about_brand',
        ),
        migrations.RemoveField(
            model_name='brandprofile',
            name='cin_registration_number',
        ),
        migrations.RemoveField(
            model_name='brandprofile',
            name='company_registration_certificate',
        ),
        migrations.RemoveField(
            model_name='brandprofile',
            name='contact_person_name',
        ),
        migrations.RemoveField(
            model_name='brandprofile',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='brandprofile',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='brandprofile',
            name='gst_certificate',
        ),
        migrations.RemoveField(
            model_name='brandprofile',
            name='gst_number',
        ),
        migrations.RemoveField(
            model_name='brandprofile',
            name='headquarters_city',
        ),
        migrations.RemoveField(
            model_name='brandprofile',
            name='headquarters_country',
        ),
        migrations.RemoveField(
            model_name='brandprofile',
            name='headquarters_state',
        ),
        migrations.RemoveField(
            model_name='brandprofile',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='brandprofile',
            name='official_email',
        ),
        migrations.RemoveField(
            model_name='brandprofile',
            name='pan_card',
        ),
        migrations.RemoveField(
            model_name='brandprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='brandprofile',
            name='whatsapp_number',
        ),
        migrations.RemoveField(
            model_name='brandprofile',
            name='whatsapp_same_as_phone',
        ),
        migrations.RemoveField(
            model_name='brandprofile',
            name='x_url',
        ),
        migrations.RemoveField(
            model_name='brandprofile',
            name='year_established',
        ),
        migrations.RemoveField(
            model_name='brandprofile',
            name='youtube_url',
        ),
    ]
