# Generated by Django 4.2.17 on 2026-08-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_remove_brandprofile_about_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandprofile',
            name='about_brand',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='cin_registration_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='company_registration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='brands/verification/'),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='facebook_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='gst_certificate',
            field=models.FileField(blank=True, null=True, upload_to='brands/verification/'),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='gst_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='headquarters_city',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='headquarters_country',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='headquarters_state',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='instagram_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to='brands/verification/'),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='x_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='year_established',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='youtube_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
