# Generated by Django 4.2.17 on 2026-08-21 05:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_brandprofile_about_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPermission',
            fields=[
                ('key', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=120)),
                ('module', models.CharField(choices=[('Dashboard', 'Dashboard'), ('Users', 'Users'), ('Roles', 'Roles'), ('Creators', 'Creators'), ('Brands', 'Brands'), ('Campaigns', 'Campaigns'), ('Shortlists', 'Shortlists'), ('Exports', 'Exports'), ('Audit Logs', 'Audit Logs'), ('Settings', 'Settings')], max_length=32)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ('module', 'key'),
            },
        ),
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('role_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_wildcard', models.BooleanField(default=False, help_text='Grants every permission, e.g. Super Admin.')),
                ('is_system', models.BooleanField(default=False, help_text='System roles cannot be deleted.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='api.adminpermission')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='useradminrole',
            name='assigned_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='api.adminrole'),
        ),
    ]
