# Generated by Django 4.2.17 on 2026-08-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_admin_role_permission_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='creator_code',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('UNVERIFIED', 'Unverified')], default='PENDING', max_length=24),
        ),
    ]
