# Generated by Django 4.2.17 on 2026-08-24 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_brand_campaign_admin_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandprofile',
            name='brand_code',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='creator_code',
        ),
    ]
