# Generated by Django 4.2.17 on 2026-08-24 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_remove_brand_creator_codes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandprofile',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='brandprofile',
            name='contact_role',
        ),
    ]
