# Generated by Django 4.2.17 on 2026-08-24 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_remove_brand_contact_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatorprofile',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='total_earnings',
        ),
    ]
