# Generated by Django 4.2.17 on 2026-08-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_remove_creator_rating_earnings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpermission',
            name='module',
            field=models.CharField(choices=[('Dashboard', 'Dashboard'), ('Users', 'Users'), ('Roles', 'Roles'), ('Creators', 'Creators'), ('Brands', 'Brands'), ('Campaigns', 'Campaigns'), ('Shortlists', 'Shortlists'), ('Exports', 'Exports')], max_length=32),
        ),
    ]
