# Generated by Django 4.2.17 on 2026-08-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_remove_audit_settings_modules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='campaign_manager',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='creators_required',
        ),
        migrations.RemoveField(
            model_name='user',
            name='account_status',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=24),
        ),
    ]
