# Generated by Django 4.2.17 on 2026-09-12 21:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_chatmessage_email_reminded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorSocialMediaPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_visible', models.BooleanField(default=False)),
                ('social_media_name', models.CharField(blank=True, default='', max_length=100)),
                ('social_media_pricing', models.PositiveIntegerField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts_pricing', to='api.creatorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CreatorPortfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('sub_title', models.CharField(blank=True, default='', max_length=255)),
                ('link', models.URLField(blank=True, default='')),
                ('video', models.FileField(blank=True, null=True, upload_to='creators/profiles/portfolio/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'webm'])])),
                ('image', models.ImageField(blank=True, null=True, upload_to='creators/profiles/portfolio/images/')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='api.creatorprofile')),
            ],
        ),
    ]
