# Generated by Django 4.2.17 on 2026-09-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0060_creator_portfolio_and_pricing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("ACTIVE", "Active"),
                    ("PAUSED", "Paused"),
                    ("COMPLETED", "Completed"),
                ],
                default="ACTIVE",
                max_length=24,
            ),
        ),
    ]
