# Generated by Django 4.2.17 on 2026-09-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0061_campaign_default_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="useradminrole",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="staff/avatars/"),
        ),
    ]
