# Generated by Django 4.2.17 on 2026-09-22 19:52

from django.db import migrations, models
import django.utils.timezone
import uuid


RATE_CARD_OPTIONS = {
    "Instagram": (
        "Instagram", "Instagram Reel", "Instagram Post", "Instagram Story",
        "Instagram Carousel", "Instagram Live", "Instagram Collab Post",
        "Instagram Reel + Story", "Instagram Post + Story", "Custom Instagram Package",
    ),
    "YouTube": (
        "YouTube", "YouTube Full Video", "YouTube Video – Up to 5 Minutes",
        "YouTube Video – Up to 10 Minutes", "YouTube Video – 10+ Minutes",
        "YouTube Shorts", "YouTube Community Post", "YouTube Live",
        "YouTube Product Integration", "YouTube Dedicated Video", "Custom YouTube Package",
    ),
    "Facebook": (
        "Facebook", "Facebook Post", "Facebook Story", "Facebook Reel", "Facebook Video",
        "Facebook Live", "Facebook Photo Post", "Facebook Link Post", "Custom Facebook Package",
    ),
    "LinkedIn": (
        "LinkedIn", "LinkedIn Post", "LinkedIn Article", "LinkedIn Video",
        "LinkedIn Image Post", "LinkedIn Newsletter", "LinkedIn Live",
        "LinkedIn Collaboration Post", "Custom LinkedIn Package",
    ),
    "X (Twitter)": (
        "X Post", "X Thread", "X Video", "X Image Post", "X Poll", "X Live", "Custom X Package",
    ),
    "Podcast": (
        "Podcast Episode", "Podcast Guest Appearance", "Podcast Interview",
        "Podcast Sponsorship", "Podcast Mention / Integration", "Podcast Short Clip",
    ),
    "Ground / Offline": (
        "Ground Report", "On-Ground Promotion", "Event Appearance", "Event Coverage",
        "Public Appearance", "Roadshow / Event Promotion", "Meet & Greet", "Ground Interview",
    ),
    "Interview / Media": (
        "Video Interview", "Audio Interview", "Written Interview", "Media Appearance",
        "Brand Interview", "Creator Interview",
    ),
}


def seed_rate_card_options(apps, schema_editor):
    RateCards = apps.get_model("api", "RateCards")
    RateCards.objects.bulk_create(
        [
            RateCards(platform=platform, service=service, sort_order=position)
            for platform, services in RATE_CARD_OPTIONS.items()
            for position, service in enumerate(services, start=1)
        ],
        ignore_conflicts=True,
    )


def unseed_rate_card_options(apps, schema_editor):
    RateCards = apps.get_model("api", "RateCards")
    for platform, services in RATE_CARD_OPTIONS.items():
        RateCards.objects.filter(platform=platform, service__in=services).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_user_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateCards',
            fields=[
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('Instagram', 'Instagram'), ('YouTube', 'YouTube'), ('Facebook', 'Facebook'), ('LinkedIn', 'LinkedIn'), ('X (Twitter)', 'X (Twitter)'), ('Podcast', 'Podcast'), ('Ground / Offline', 'Ground / Offline'), ('Interview / Media', 'Interview / Media'), ('Other', 'Other')], max_length=32)),
                ('service', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'rate card',
                'verbose_name_plural': 'rate cards',
                'ordering': ('platform', 'sort_order', 'service'),
            },
        ),
        migrations.AddConstraint(
            model_name='ratecards',
            constraint=models.UniqueConstraint(fields=('platform', 'service'), name='unique_rate_card_platform_service'),
        ),
        migrations.RunPython(seed_rate_card_options, unseed_rate_card_options),
    ]
