# Generated by Django 4.2.17 on 2026-09-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_rate_card_catalog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratecards',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='ratecards',
            name='unique_rate_card_platform_service',
        ),
        migrations.RemoveField(
            model_name='ratecards',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='ratecards',
            name='platform',
            field=models.CharField(max_length=32),
        ),
    ]
