# Generated by Django 4.2.17 on 2026-09-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0065_creator_rate_card_pricing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminpermission",
            name="module",
            field=models.CharField(
                choices=[
                    ("Dashboard", "Dashboard"),
                    ("Users", "Users"),
                    ("Roles", "Roles"),
                    ("Rate Cards", "Rate Cards"),
                    ("Creators", "Creators"),
                    ("Brands", "Brands"),
                    ("Campaigns", "Campaigns"),
                    ("Shortlists", "Shortlists"),
                    ("Exports", "Exports"),
                ],
                max_length=32,
            ),
        ),
    ]
