# Generated by Django 4.2.17 on 2026-09-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_campaignworksubmission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaignworksubmission',
            options={},
        ),
        migrations.RemoveField(
            model_name='campaignworksubmission',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='campaignworksubmission',
            name='attachment_url',
        ),
        migrations.RemoveField(
            model_name='campaignworksubmission',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='campaignworksubmission',
            name='creator_remarks',
        ),
        migrations.RemoveField(
            model_name='campaignworksubmission',
            name='submitted_at',
        ),
        migrations.AlterField(
            model_name='campaignworksubmission',
            name='screenshot_url',
            field=models.FileField(blank=True, null=True, upload_to='Creator/Campain/work-delivery'),
        ),
        migrations.AlterField(
            model_name='campaignworksubmission',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('REVISION_REQUESTED', 'Revision requested'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='UNDER_REVIEW', max_length=24),
        ),
    ]
