# Generated by Django 4.2.17 on 2026-09-27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0069_campaignworksubmission_submission_files"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="email_reminded_at",
        ),
    ]
