export interface SchoolStudent {
  id: string;
  studentUserId?: string;
  firstName: string;
  middleName?: string;
  lastName: string;
  email?: string;
  phoneNo?: string;
  gender: 'Male' | 'Female' | 'Other';
  dob: string;
  bloodGroup: string;
  nationality?: string;
  religion?: string;
  category?: string;
  photo?: string;
  admissionNo: string;
  admissionDate: string;
  admissionStatus?: string;
  admissionType?: string;
  appliedForClass?: string;
  academicYear?: string;
  className: string;
  classId?: string;
  section: string;
  sectionId?: string;
  rollNo: number;
  rollNoText?: string;
  enrollmentId?: string;
  enrollmentStatus?: boolean;
  status: 'Active' | 'On Leave' | 'Suspended' | 'Alumni';
  fatherName: string;
  motherName: string;
  guardianName?: string;
  guardians?: Array<{
    id?: string;
    name: string;
    relation: string;
    phoneNo: string;
    email?: string;
    occupation?: string;
  }>;
  parentPhone: string;
  address: string;
  addressLine2?: string;
  city: string;
  state: string;
  country?: string;
  pincode: string;
  documents?: Array<{
    id?: string;
    documentType: string;
    fileUrl: string;
  }>;
  feeAccountId?: string;
  feeTotalDue?: number;
  feeTotalPaid?: number;
  feeBalance?: number;
  feeStatus?: string;
  allergies?: string;
  medicalNotes?: string;
}
